FROM php:8.3-cli

RUN apt-get update \
    && apt-get install -y --no-install-recommends $PHPIZE_DEPS libpq-dev unzip \
    && docker-php-ext-install pdo_pgsql \
    && pecl install pcov \
    && docker-php-ext-enable pcov \
    && apt-get purge -y --auto-remove $PHPIZE_DEPS \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app
